spring.application.name=demo

# Server Configuration
server.port=8084

# Aiven MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysql-2f50da93-college-courseregistration-portal.d.aivencloud.com:23232/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson / JSON Configuration
spring.jackson.serialization.fail-on-empty-beans=false